version: '3.9'
services:
  hasura-starter:
    image: hasura/graphql-engine
    container_name: hasura-starter
    ports:
    - "8080:8080"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:123456@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: t1ger1
      ## Custom variables
      ACCOUNT_DB_URL: postgres://postgres:123456@postgres:5432/account
      PRODUCT_DB_URL: postgres://postgres:123456@postgres:5432/product
      ORDER_DB_URL: postgres://postgres:123456@postgres:5432/orders
      PAYMENT_DB_URL: postgres://postgres:123456@postgres:5432/payment
      REPORT_DB_URL: postgres://postgres:123456@postgres:5432/report
    networks:
      - common

networks:
  common:
    external: true